"""
waveforms_tools.py

Utility functions for analytic feature extraction from 1D waveforms (time-series arrays).

Designed to work with the waveforms generated by create_synthetic_waveforms.ipynb.

Exported functions
------------------
get_integral         : compute the integral (sum of samples) of one or more waveforms.
get_rms              : compute the RMS of the leading samples of one or more waveforms.
get_peak             : find the highest peak amplitude for each waveform in an array.
get_quantile_indices : return indices of waveforms whose feature value falls between two quantiles.
"""

import numpy as np
from scipy.signal import find_peaks

def get_integral(wfs, whole=True, gate=500, start=0):
    """
    Compute the integral (sum of samples) of one or more waveforms.

    Parameters
    ----------
    wfs   : np.ndarray
        Single waveform (1D) or array of waveforms (2D, shape: [n_wfs, n_samples]).
    whole : bool, optional (default=True)
        If True, integrates over all samples of each waveform.
        If False, integrates only over a window of length `gate` starting at `start`.
    gate  : int, optional (default=500)
        Number of samples to include in the integration window. Used only if whole=False.
    start : int, optional (default=0)
        Index of the first sample of the integration window. Used only if whole=False.

    Returns
    -------
    np.ndarray or scalar
        For 2D input: 1D array of integral values, one per waveform.
        For 1D input: scalar integral value.
    """
    if (wfs.ndim > 1 & whole == True):
        return np.sum(wfs[:,0:-1], axis=1)
    elif (wfs.ndim > 1 & whole != True):
        return np.sum(wfs[:,int(start):int(start+gate)], axis=1)
    elif (wfs.ndim <= 1 & whole == True):
        return np.sum(wfs)
    else:
        return np.sum(wfs[:,int(start):int(start+gate)])


def get_rms(wfs, gate=500):
    """
    Compute the RMS (standard deviation) of one or more waveforms
    over their first `gate` samples. Useful as a noise estimator
    when the baseline occupies the beginning of the waveform.

    Parameters
    ----------
    wfs  : np.ndarray
        Single waveform (1D) or array of waveforms (2D, shape: [n_wfs, n_samples]).
    gate : int, optional (default=500)
        Number of leading samples over which the RMS is computed.

    Returns
    -------
    np.ndarray or scalar
        For 2D input: column array of RMS values (shape: [n_samples, 1]), one per waveform.
        For 1D input: scalar RMS value.
    """
    if wfs.ndim > 1:
        return np.std(wfs[:,0:gate], axis=1).reshape((-1, 1))
    else:
        return np.std(wfs[0:gate])


def find_wf_peak(wf):
    """
    Find the highest peak in a single waveform.

    A peak is defined as a local maximum by scipy.signal.find_peaks
    with no additional constraints on prominence or width.
    If no peaks are found, the function returns [0] as a fallback.

    Parameters
    ----------
    wf : np.ndarray
        1D array representing a single waveform.

    Returns
    -------
    list of float
        Single-element list containing the amplitude of the highest peak.
        Returns 0 if no peaks are detected.
    """
    peaks, _ = find_peaks(wf)
    if len(peaks) > 0:
        highest_peak = wf[peaks[np.argmax(wf[peaks])]]
    else:
        highest_peak = 0
    return highest_peak


def get_peak(wfs):
    """
    Find the highest peak for each waveform in an array of waveforms.
    Applies find_wf_peak to every row of the input array.

    Parameters
    ----------
    wfs : np.ndarray
        2D array of waveforms (shape: [n_wfs, n_samples]).

    Returns
    -------
    np.ndarray
        1D array of peak amplitudes (shape: [n_samples]),
        one value per waveform.
    """
    highest_peaks = [find_wf_peak(wf) for wf in wfs]
    return np.array(highest_peaks)


def get_quantile_indices(values, q1=0.80, q2=0.90):
    """
    Return the indices of elements in a 1D array whose values fall
    between two quantiles (inclusive on both ends).

    Parameters
    ----------
    values : np.ndarray
        1D array of values to filter (e.g. peak amplitudes or integrals).
    q1     : float
        Lower quantile bound, in the range [0, 1]. E.g. 0.25 for the 25th percentile.
    q2     : float
        Upper quantile bound, in the range [0, 1]. E.g. 0.75 for the 75th percentile.

    Returns
    -------
    np.ndarray
        1D array of indices where values[i] >= lower_bound and values[i] <= upper_bound.

    Example
    -------
    indices = get_quantile_indices(pksAmp, q1=0.25, q2=0.75)
    selected_waveforms = train_gamma_wave[indices]
    """
    assert values.ndim == 1,    "values must be a 1D array"
    assert 0.0 <= q1 <= 1.0,    "q1 must be in [0, 1]"
    assert 0.0 <= q2 <= 1.0,    "q2 must be in [0, 1]"
    assert q1 < q2,             "q1 must be strictly less than q2"

    lower_bound = np.quantile(values, q1)
    upper_bound = np.quantile(values, q2)

    return np.where((values >= lower_bound) & (values <= upper_bound))[0]
